name: release

on:
  push:
    tags:
      - v*

env:
  GO_VERSION: "1.21.0"

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: oven-sh/setup-bun@v2

      - name: Build WASM
        run: go build -ldflags="-s -w" -v -o frontend/static/calculator.wasm ./wasm
        env:
          GOOS: js
          GOARCH: wasm

      - name: Install root dependencies
        run: bun install

      - name: Build and package
        run: bun run dist:mac

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: oven-sh/setup-bun@v2

      - name: Build WASM
        run: go build -ldflags="-s -w" -v -o frontend/static/calculator.wasm ./wasm
        env:
          GOOS: js
          GOARCH: wasm

      - name: Install root dependencies
        run: bun install

      - name: Build and package
        run: bun run dist:win

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
